### ISSUE TITLE
What‘s the meaning of “consistent voting”?

### ISSUE THREAD

**Issue by bogeyixiu** [zhulf0804/NgeNet#10]
First of all, thank you for sharing, I feel I have learned a lot. But I would like to ask about the meaning of "consistent" in "consistent voting". Is there any "non-consistent"?

**Comment by zhulf0804** [comment]
Hi @bogeyixiu,

Thanks for your interest. 

For example, non-consistent features are generally located in plane region 3DMatch, where the target points found through the multi-scale features are not consistent. Because features of plane region may not be represented well for matching.

Here, we visualize consistent points (red) and non-consistent points (green) in one sampled source point cloud as follows:

<img width="1287" alt="Screen Shot 2022-09-24 at 3 03 14 PM" src="https://user-images.githubusercontent.com/36033208/192084842-60a64b88-6e5a-4343-b316-ccdb83b7c6c4.png">

We can roughly sense their location distribution.

Best regards.

**Comment by bogeyixiu** [comment]
Thank you very much for your reply, I have benefited a lot. Thanks again!
