### ISSUE TITLE
No such file or directory: './3dmatch/test/7-scenes-redkitchen/cloud_bin_1.pth'

### ISSUE THREAD

**Issue by zhirihuixin** [zhulf0804/NgeNet#2]
Thank you for sharing your work. 

When performing the test procedure on 3dmatch dataset，I got error

`FileNotFoundError: [Errno 2] No such file or directory: './3dmatch/test/7-scenes-redkitchen/cloud_bin_1.pth'`

There are only *.ply and *.txt in 3dmatch dataset, not *.pth. what should I do

**Comment by zhulf0804** [comment]
Thank you for your interest.

Because we conducted experiments on both 3DMatch and 3DLoMatch, we utilized [3DMatch and 3DLoMatch](https://github.com/zhulf0804/NgeNet#dataset) dataset which was provided by [PREDATOR](https://github.com/prs-eth/OverlapPredator). And I just confirmed that *.pth and *.txt are involved, not *.ply. 

And did you use the same 3DMatch dataset ?

Best regards.

**Comment by zhirihuixin** [comment]
Thank you for your response. This is a screenshot of the prs-eth/OverlapPredator README.
![微信截图_20220429094148](https://user-images.githubusercontent.com/17866939/165873125-ba322f64-38ca-4aae-bffa-4228f1f6aadf.png)
I've downloaded `3dmatch.zip` from `https://share.phys.ethz.ch/~gsg/pairwise_reg/3dmatch.zip`.  I got the same result as the screenshot.

**Comment by zhulf0804** [comment]
Yes, this is the raw dense 3DMatch data.

Please download the processed 3DMatch data from [https://share.phys.ethz.ch/~gsg/Predator/data.zip](https://share.phys.ethz.ch/~gsg/Predator/data.zip). More details can be seen [here](https://github.com/prs-eth/OverlapPredator/blob/main/scripts/download_data_weight.sh). 

Thank you for you to point out this mistake about dataset url. I'll update the url link in README.md as soon as possible.

Best regards.

**Comment by zhirihuixin** [comment]
Thanks for solving my question.

Best regards.
